branch name modify and Account app models.py, views.py complete
wecode-bootcamp-korea/9-hojitech-backend pull request #2
Opened 2020-06-26 13:11 UTC by kljopu

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
브랜치 이름이 통일되지 않아 feature/account로 수정하였습니다. 또한 account 앱의 모델과 뷰를 구현하였습니다.  
         
		 
## 수정 사항들 자세한 내용
로그인 데코레이터와 회원가입 시 정규식을 적용하였습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [O] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [O] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [O] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [O] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-27 11:53 UTC, soheon-lee commented
컨플릭트 해결해주세요

2020-06-29 02:53 UTC, evergreen-david requested changes

2020-06-29 02:53 UTC, evergreen-david commented on account/models.py
> +
파일의 끝은 한줄만 남도록 정리 부탁 드립니다.

2020-06-29 02:53 UTC, evergreen-david commented on account/models.py
> +        db_table    =       "Accounts"
테이블 이름은 클래스처럼 대문자로 시작하지 않습니다. 따라서 accounts로 변경 부탁 드립니다.

2020-06-29 02:53 UTC, evergreen-david commented on account/urls.py
> +	path('signin', SignInView.as_view())
```suggestion
	path('sign-up', SignUpView.as_view()),
	path('sign-in', SignInView.as_view())
```

2020-06-29 02:53 UTC, evergreen-david commented on account/views.py
> +            print("login succeed")
프린트문은 테스트할때만 사용하고 정리해주세요,.

2020-06-29 02:53 UTC, evergreen-david commented on account/views.py
> +                token = jwt.encode({'id': account.id}, SECRET_KEY, algorithm ="HS256")
알고리즘 방식도 SECRET_KEY 처럼 my_settings에 관리 부탁 드립니다.

2020-06-29 03:03 UTC, devops-andrew requested changes

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                print("email is already exists")
print 제거요

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +
공백 제거해주세요.

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +
공백 제거요

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +            if Account.objects.filter(email = data['email']).exists():      # email 존재 여부 확인
코드로 설명되는 부분은 주석치지 말아주세요.

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +            else:       # email 등록 가능, 정규식 확인 시작
else제거하시고, 아래 코드들 한탭씩 당겨주세요.

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                        password = password_bcrypt.decode('utf-8')
위의 세줄을
```
password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
```
이렇게 줄일수 있겠네요.

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                    print("email validation" ,email_validation.match(data['email']))
제거해주세요.

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                        Account.objects.create(email=data['email'], password=password, first_name=data['first_name'], last_name=data['last_name'])
```suggestion
                        Account.objects.create(
                            email=data['email'], 
                            password=password, 
                            first_name=data['first_name'], 
                            last_name=data['last_name']
                        )
```

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                        return JsonResponse( { "message" : "SignUp Success!" }, status = 200 )
꼭 줘야하는 메세지 아니라면 
```suggestion
                        return HttpResponse( status = 200 )
```

2020-06-29 03:03 UTC, devops-andrew commented on account/views.py
> +                        return JsonResponse( { "message" : "Password Validation Failed" }, status = 400 )
```suggestion
                        return JsonResponse( { "message" : "INVALID_PASSWORD" }, status = 400 )
```

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +                    return JsonResponse( { "message" : "Email Validation Failed!" }, status = 400 )
```suggestion
                    return JsonResponse( { "message" : "INVALID_EMAIL" }, status = 400 )
```

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +# login decorator
제거해주세요.

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +def decorator_login(func):
데코레이터는 여기에 두지마시고, 범용성을 위해 별도의 account 앱 디렉토리 내부에 utils.py라는 파일에 따로 코드를 저장하고 임포트 해서 사용해주세요.

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +            print("login succeed")
print 제거요

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +            return JsonResponse({"Error Message": "Invalid_token"}, status = 400)
```suggestion
            return JsonResponse({"message": "INVALID_TOKEN"}, status = 400)
```

2020-06-29 03:03 UTC, ulfrid commented on account/views.py
> +        except ObjectDoesNotExist:
```suggestion
        except Account.DoesNotExist:
```

2020-06-29 05:51 UTC, soheon-lee commented on account/views.py
>  from django.shortcuts import render
사용하지 않는 코드입니다. 저게해주세요.

2020-06-29 06:46 UTC, soheon-lee commented
LGTM

2020-06-29 06:46 UTC, merged